# AutoDock-Vina-Docker
# https://github.com/Metaphorme/AutoDock-Vina-Docker
# MIT License
# Copyright (c) 2022 Metaphorme <https://github.com/Metaphorme>


FROM ubuntu:latest as builder

ARG BRANCHES

RUN /bin/bash -c " \
    set -ex \
    && apt-get update; apt-get install -y swig curl build-essential git libboost-all-dev \
    && git clone https://github.com/reshetovdenis/AutoDock-Vina /app/AutoDock-Vina \
    && cd /app/AutoDock-Vina; git checkout e3b7cde2ee27dd035252470b869f06e9b72ff3ed \
    && cd /app/AutoDock-Vina/build/linux/release; make \
    "


FROM scratch

ARG BRANCHES

LABEL org.opencontainers.image.authors="Metaphorme" \
      org.opencontainers.image.document="https://github.com/Metaphorme/AutoDock-Vina-Docker" \
      org.opencontainers.image.description="Build from ${BRANCHES}" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.name="vina"

COPY --from=builder /app/AutoDock-Vina/build/linux/release/vina /
COPY --from=builder /app/AutoDock-Vina/build/linux/release/vina_split /

VOLUME /data

WORKDIR /data

ENV PATH=$PATH:/:/data/
